name = "synack_misc"
description = "Shiny new project"
version = "0.1.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

[[depends-on]]  # Added by alr
hal = "~0.3.0"  # Added by alr
[[depends-on]]  # Added by alr
chests = "~0.1.1"  # Added by alr
