name = "synack_misc"
description = "Misc packages for embedded"
version = "0.2.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
licenses = "BSD-3-Clause"
website = ""
tags = []

[[depends-on]]
chests = "~0.1.1"
hal = "~0.3.0"
